# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [linux-x64, win-x64, osx-arm64]

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: dotnet publish Embe7.Hl7.Util -r ${{matrix.arch}} -o ${{matrix.arch}}
    - name: Zip
      run: zip -j ${{matrix.arch}}-${{github.ref_name}}.zip ${{matrix.arch}}/*
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{matrix.arch}}-${{github.ref_name}}.zip
  pack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Pack
      run: dotnet pack Embe7.sln -o out
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: out/*
